name: Mirror the repo
on: [ push ]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: mirror in gitlab
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: 'https://gitlab.com/anas-elgarhy/eelu-login.git'
          GIT_USERNAME: anas-elgarhy
          GIT_PASSWORD: ${{ secrets.GITLAP_TOKEN }}

      - name: mirror in bitbucket
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: 'https://anas-elgarhy@bitbucket.org/anas_elgarhy/eelu-login.git'
          REMOTE_NAME: bitbucket
          GIT_USERNAME: anas_elgarhy
          GIT_PASSWORD: ${{ secrets.BITBUCKET_TOKEN }}

      - name: mirror in codeberg
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: 'https://codeberg.org/anas-elgarhy/eelu-login.git'
          REMOTE_NAME: codeberg
          GIT_USERNAME: anas-elgarhy
          GIT_PASSWORD: ${{ secrets.CODEBERG_TOKEN }}

      - name: mirror in git.disroot
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: 'https://git.disroot.org/anas-elgarhy/eelu-login.git'
          REMOTE_NAME: disroot
          GIT_USERNAME: anas-elgarhy
          GIT_PASSWORD: ${{ secrets.DISROOT_TOKEN }}
